DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS passwords;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  pass TEXT NOT NULL
);

CREATE TABLE record (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  palvelu TEXT NOT NULL,
  username TEXT NOT NULL,
  pass TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);